# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Usage
  items:
    - label: 'Clubhouse Inspirations'
      link: '/components/clubhouse'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/ACGCET/nutro-components-react
